// src/app/layout.tsx

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from '@/components/Navbar';
import PreLoader from '@/components/Preloader';
import { TailwindIndicator } from '@/components/debugger/tailwindIndicator';
import { AppProvider } from '../components/context/AppContext';
import Head from 'next/head';
import { Providers } from './provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="viewport-fit=cover" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <title>Halord Portfolio</title>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-x-clip overflow-y-clip bg-mainbody-weg antialiased scrollbar-hide`}
      >
        <Providers>
          <AppProvider>
            <TailwindIndicator />
            <PreLoader />
            <Navbar />
            {children}
          </AppProvider>
        </Providers>
      </body>
    </html>
  );
}
